# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Optracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optrackertable',
            old_name='impact_summary',
            new_name='comment',
        ),
    ]
