# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Optracker', '0002_auto_20180804_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optrackertable',
            name='type_of_idea',
            field=models.CharField(choices=[('PROCESS', 'Process'), ('TOOL', 'Tool')], default=None, max_length=10, null=True),
        ),
    ]
