# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Optracker', '0004_auto_20180804_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='optrackertable',
            name='file_upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files_uploaded'),
            preserve_default=False,
        ),
    ]
